// Code generated by protoc-gen-go. DO NOT EDIT.
// source: debug/debug.proto

package debug

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The top-level message sent by the client for the `StreamingOpen` method.
// Multiple `StreamingOpenReq` messages can be sent but the first message
// must contain a `debug_config` message to initialize the debug session.
// All subsequent messages must contain bytes to be sent to the debug session
// and must not contain a `session_config` message.
type StreamingOpenReq struct {
	// Content must be either a debug session config or data to be sent.
	//
	// Types that are valid to be assigned to Content:
	//	*StreamingOpenReq_DebugConfig
	//	*StreamingOpenReq_Data
	Content              isStreamingOpenReq_Content `protobuf_oneof:"content"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *StreamingOpenReq) Reset()         { *m = StreamingOpenReq{} }
func (m *StreamingOpenReq) String() string { return proto.CompactTextString(m) }
func (*StreamingOpenReq) ProtoMessage()    {}
func (*StreamingOpenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ae24eab94cb53d5, []int{0}
}

func (m *StreamingOpenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingOpenReq.Unmarshal(m, b)
}
func (m *StreamingOpenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingOpenReq.Marshal(b, m, deterministic)
}
func (m *StreamingOpenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingOpenReq.Merge(m, src)
}
func (m *StreamingOpenReq) XXX_Size() int {
	return xxx_messageInfo_StreamingOpenReq.Size(m)
}
func (m *StreamingOpenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingOpenReq.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingOpenReq proto.InternalMessageInfo

type isStreamingOpenReq_Content interface {
	isStreamingOpenReq_Content()
}

type StreamingOpenReq_DebugConfig struct {
	DebugConfig *DebugConfig `protobuf:"bytes,1,opt,name=debugConfig,proto3,oneof"`
}

type StreamingOpenReq_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*StreamingOpenReq_DebugConfig) isStreamingOpenReq_Content() {}

func (*StreamingOpenReq_Data) isStreamingOpenReq_Content() {}

func (m *StreamingOpenReq) GetContent() isStreamingOpenReq_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *StreamingOpenReq) GetDebugConfig() *DebugConfig {
	if x, ok := m.GetContent().(*StreamingOpenReq_DebugConfig); ok {
		return x.DebugConfig
	}
	return nil
}

func (m *StreamingOpenReq) GetData() []byte {
	if x, ok := m.GetContent().(*StreamingOpenReq_Data); ok {
		return x.Data
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StreamingOpenReq) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StreamingOpenReq_DebugConfig)(nil),
		(*StreamingOpenReq_Data)(nil),
	}
}

// Tells the session which target to open and provides additional parameters
// that might be needed to configure the target or the monitor itself.
type DebugConfig struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DebugConfig) Reset()         { *m = DebugConfig{} }
func (m *DebugConfig) String() string { return proto.CompactTextString(m) }
func (*DebugConfig) ProtoMessage()    {}
func (*DebugConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ae24eab94cb53d5, []int{1}
}

func (m *DebugConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebugConfig.Unmarshal(m, b)
}
func (m *DebugConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebugConfig.Marshal(b, m, deterministic)
}
func (m *DebugConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebugConfig.Merge(m, src)
}
func (m *DebugConfig) XXX_Size() int {
	return xxx_messageInfo_DebugConfig.Size(m)
}
func (m *DebugConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_DebugConfig.DiscardUnknown(m)
}

var xxx_messageInfo_DebugConfig proto.InternalMessageInfo

func (m *DebugConfig) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

//
type StreamingOpenResp struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingOpenResp) Reset()         { *m = StreamingOpenResp{} }
func (m *StreamingOpenResp) String() string { return proto.CompactTextString(m) }
func (*StreamingOpenResp) ProtoMessage()    {}
func (*StreamingOpenResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ae24eab94cb53d5, []int{2}
}

func (m *StreamingOpenResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingOpenResp.Unmarshal(m, b)
}
func (m *StreamingOpenResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingOpenResp.Marshal(b, m, deterministic)
}
func (m *StreamingOpenResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingOpenResp.Merge(m, src)
}
func (m *StreamingOpenResp) XXX_Size() int {
	return xxx_messageInfo_StreamingOpenResp.Size(m)
}
func (m *StreamingOpenResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingOpenResp.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingOpenResp proto.InternalMessageInfo

func (m *StreamingOpenResp) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// TODO duplicated from rpc/commands/common.proto
type Instance struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Instance) Reset()         { *m = Instance{} }
func (m *Instance) String() string { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()    {}
func (*Instance) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ae24eab94cb53d5, []int{3}
}

func (m *Instance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instance.Unmarshal(m, b)
}
func (m *Instance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instance.Marshal(b, m, deterministic)
}
func (m *Instance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instance.Merge(m, src)
}
func (m *Instance) XXX_Size() int {
	return xxx_messageInfo_Instance.Size(m)
}
func (m *Instance) XXX_DiscardUnknown() {
	xxx_messageInfo_Instance.DiscardUnknown(m)
}

var xxx_messageInfo_Instance proto.InternalMessageInfo

func (m *Instance) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*StreamingOpenReq)(nil), "cc.arduino.cli.debug.StreamingOpenReq")
	proto.RegisterType((*DebugConfig)(nil), "cc.arduino.cli.debug.DebugConfig")
	proto.RegisterType((*StreamingOpenResp)(nil), "cc.arduino.cli.debug.StreamingOpenResp")
	proto.RegisterType((*Instance)(nil), "cc.arduino.cli.debug.Instance")
}

func init() { proto.RegisterFile("debug/debug.proto", fileDescriptor_5ae24eab94cb53d5) }

var fileDescriptor_5ae24eab94cb53d5 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x14, 0x84, 0xe3, 0x88, 0x42, 0x79, 0x29, 0x88, 0x5a, 0x1d, 0xaa, 0x0e, 0xa8, 0x78, 0xa0, 0x11,
	0x12, 0x0e, 0x2a, 0x1b, 0x63, 0x01, 0xa9, 0x9d, 0x90, 0xcc, 0xc6, 0xe6, 0xd8, 0x6e, 0xb0, 0xd4,
	0xda, 0x26, 0x71, 0x16, 0x7e, 0x3d, 0xc2, 0x4d, 0xa1, 0x44, 0x19, 0x58, 0x12, 0x59, 0x77, 0xdf,
	0xbb, 0xb3, 0x1f, 0x0c, 0xa5, 0xca, 0xeb, 0x22, 0x0b, 0x5f, 0xea, 0x4a, 0xeb, 0x2d, 0x1e, 0x09,
	0x41, 0x79, 0x29, 0x6b, 0x6d, 0x2c, 0x15, 0x1b, 0x4d, 0x83, 0x46, 0x3e, 0xe1, 0xe2, 0xd5, 0x97,
	0x8a, 0x6f, 0xb5, 0x29, 0x5e, 0x9c, 0x32, 0x4c, 0x7d, 0xe0, 0x67, 0x48, 0x82, 0xf8, 0x68, 0xcd,
	0x5a, 0x17, 0x63, 0x34, 0x45, 0x69, 0x32, 0xbf, 0xa2, 0x5d, 0x3c, 0x7d, 0xfa, 0x35, 0x2e, 0x23,
	0x76, 0xc8, 0xe1, 0x11, 0x1c, 0x49, 0xee, 0xf9, 0x38, 0x9e, 0xa2, 0x74, 0xb0, 0x8c, 0x58, 0x38,
	0x2d, 0x4e, 0xe1, 0x44, 0x58, 0xe3, 0x95, 0xf1, 0x64, 0x05, 0xc9, 0x01, 0x8e, 0x1f, 0xa0, 0xaf,
	0x4d, 0xe5, 0xb9, 0x11, 0xaa, 0xc9, 0xbc, 0xec, 0xce, 0x5c, 0x35, 0x2e, 0xf6, 0xe3, 0x27, 0x33,
	0x18, 0xb6, 0xae, 0x51, 0x39, 0x8c, 0x9b, 0x02, 0xdf, 0xc3, 0x06, 0xbb, 0x78, 0x32, 0x81, 0xfe,
	0x1e, 0xc7, 0xe7, 0x10, 0x6b, 0x19, 0xd4, 0x1e, 0x8b, 0xb5, 0x9c, 0x5b, 0xe8, 0x85, 0x3e, 0x78,
	0x0d, 0x67, 0x7f, 0xa6, 0xe1, 0xeb, 0xee, 0x22, 0xed, 0x97, 0x9b, 0xcc, 0xfe, 0xe5, 0xab, 0x1c,
	0x89, 0x52, 0x74, 0x87, 0x16, 0x37, 0x6f, 0x69, 0xa1, 0xfd, 0x7b, 0x9d, 0x53, 0x61, 0xb7, 0x59,
	0xc3, 0xed, 0xff, 0xb7, 0x62, 0xa3, 0xb3, 0xd2, 0x89, 0xdd, 0x12, 0xf3, 0xe3, 0xb0, 0xc5, 0xfb,
	0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa1, 0xf5, 0xa7, 0x7a, 0xda, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DebugClient is the client API for Debug service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DebugClient interface {
	StreamingOpen(ctx context.Context, opts ...grpc.CallOption) (Debug_StreamingOpenClient, error)
}

type debugClient struct {
	cc *grpc.ClientConn
}

func NewDebugClient(cc *grpc.ClientConn) DebugClient {
	return &debugClient{cc}
}

func (c *debugClient) StreamingOpen(ctx context.Context, opts ...grpc.CallOption) (Debug_StreamingOpenClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Debug_serviceDesc.Streams[0], "/cc.arduino.cli.debug.Debug/StreamingOpen", opts...)
	if err != nil {
		return nil, err
	}
	x := &debugStreamingOpenClient{stream}
	return x, nil
}

type Debug_StreamingOpenClient interface {
	Send(*StreamingOpenReq) error
	Recv() (*StreamingOpenResp, error)
	grpc.ClientStream
}

type debugStreamingOpenClient struct {
	grpc.ClientStream
}

func (x *debugStreamingOpenClient) Send(m *StreamingOpenReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *debugStreamingOpenClient) Recv() (*StreamingOpenResp, error) {
	m := new(StreamingOpenResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DebugServer is the server API for Debug service.
type DebugServer interface {
	StreamingOpen(Debug_StreamingOpenServer) error
}

func RegisterDebugServer(s *grpc.Server, srv DebugServer) {
	s.RegisterService(&_Debug_serviceDesc, srv)
}

func _Debug_StreamingOpen_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DebugServer).StreamingOpen(&debugStreamingOpenServer{stream})
}

type Debug_StreamingOpenServer interface {
	Send(*StreamingOpenResp) error
	Recv() (*StreamingOpenReq, error)
	grpc.ServerStream
}

type debugStreamingOpenServer struct {
	grpc.ServerStream
}

func (x *debugStreamingOpenServer) Send(m *StreamingOpenResp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *debugStreamingOpenServer) Recv() (*StreamingOpenReq, error) {
	m := new(StreamingOpenReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Debug_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cc.arduino.cli.debug.Debug",
	HandlerType: (*DebugServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamingOpen",
			Handler:       _Debug_StreamingOpen_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "debug/debug.proto",
}
