// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commands/debug.proto

package commands

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The top-level message sent by the client for the `StreamingOpen` method.
// Multiple `StreamingOpenReq` messages can be sent but the first message
// must contain a `debug_config` message to initialize the debug session.
// All subsequent messages must contain bytes to be sent to the debug session
// and must not contain a `session_config` message.
type StreamingOpenReq struct {
	// Content must be either a debug session config or data to be sent.
	//
	// Types that are valid to be assigned to Content:
	//	*StreamingOpenReq_CompileReq
	//	*StreamingOpenReq_Data
	Content              isStreamingOpenReq_Content `protobuf_oneof:"content"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *StreamingOpenReq) Reset()         { *m = StreamingOpenReq{} }
func (m *StreamingOpenReq) String() string { return proto.CompactTextString(m) }
func (*StreamingOpenReq) ProtoMessage()    {}
func (*StreamingOpenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4d863c41e6da83c, []int{0}
}

func (m *StreamingOpenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingOpenReq.Unmarshal(m, b)
}
func (m *StreamingOpenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingOpenReq.Marshal(b, m, deterministic)
}
func (m *StreamingOpenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingOpenReq.Merge(m, src)
}
func (m *StreamingOpenReq) XXX_Size() int {
	return xxx_messageInfo_StreamingOpenReq.Size(m)
}
func (m *StreamingOpenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingOpenReq.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingOpenReq proto.InternalMessageInfo

type isStreamingOpenReq_Content interface {
	isStreamingOpenReq_Content()
}

type StreamingOpenReq_CompileReq struct {
	CompileReq *CompileReq `protobuf:"bytes,1,opt,name=compileReq,proto3,oneof"`
}

type StreamingOpenReq_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*StreamingOpenReq_CompileReq) isStreamingOpenReq_Content() {}

func (*StreamingOpenReq_Data) isStreamingOpenReq_Content() {}

func (m *StreamingOpenReq) GetContent() isStreamingOpenReq_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *StreamingOpenReq) GetCompileReq() *CompileReq {
	if x, ok := m.GetContent().(*StreamingOpenReq_CompileReq); ok {
		return x.CompileReq
	}
	return nil
}

func (m *StreamingOpenReq) GetData() []byte {
	if x, ok := m.GetContent().(*StreamingOpenReq_Data); ok {
		return x.Data
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StreamingOpenReq) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StreamingOpenReq_CompileReq)(nil),
		(*StreamingOpenReq_Data)(nil),
	}
}

//
type StreamingOpenResp struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingOpenResp) Reset()         { *m = StreamingOpenResp{} }
func (m *StreamingOpenResp) String() string { return proto.CompactTextString(m) }
func (*StreamingOpenResp) ProtoMessage()    {}
func (*StreamingOpenResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4d863c41e6da83c, []int{1}
}

func (m *StreamingOpenResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingOpenResp.Unmarshal(m, b)
}
func (m *StreamingOpenResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingOpenResp.Marshal(b, m, deterministic)
}
func (m *StreamingOpenResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingOpenResp.Merge(m, src)
}
func (m *StreamingOpenResp) XXX_Size() int {
	return xxx_messageInfo_StreamingOpenResp.Size(m)
}
func (m *StreamingOpenResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingOpenResp.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingOpenResp proto.InternalMessageInfo

func (m *StreamingOpenResp) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*StreamingOpenReq)(nil), "cc.arduino.cli.commands.StreamingOpenReq")
	proto.RegisterType((*StreamingOpenResp)(nil), "cc.arduino.cli.commands.StreamingOpenResp")
}

func init() { proto.RegisterFile("commands/debug.proto", fileDescriptor_a4d863c41e6da83c) }

var fileDescriptor_a4d863c41e6da83c = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0xce, 0xcf, 0xcd,
	0x4d, 0xcc, 0x4b, 0x29, 0xd6, 0x4f, 0x49, 0x4d, 0x2a, 0x4d, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x12, 0x4f, 0x4e, 0xd6, 0x4b, 0x2c, 0x4a, 0x29, 0xcd, 0xcc, 0xcb, 0xd7, 0x4b, 0xce, 0xc9,
	0xd4, 0x83, 0x29, 0x92, 0x12, 0x85, 0x2b, 0x07, 0x31, 0xf2, 0xf3, 0x20, 0xea, 0xa5, 0xc4, 0x90,
	0x85, 0x0b, 0x32, 0x73, 0x52, 0x21, 0xe2, 0x4a, 0x55, 0x5c, 0x02, 0xc1, 0x25, 0x45, 0xa9, 0x89,
	0xb9, 0x99, 0x79, 0xe9, 0xfe, 0x05, 0xa9, 0x79, 0x41, 0xa9, 0x85, 0x42, 0xae, 0x5c, 0x5c, 0x50,
	0x45, 0x41, 0xa9, 0x85, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0xca, 0x7a, 0x38, 0x2c, 0xd4,
	0x73, 0x86, 0x2b, 0xf5, 0x60, 0x08, 0x42, 0xd2, 0x28, 0x24, 0xc2, 0xc5, 0x92, 0x92, 0x58, 0x92,
	0x28, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0xe3, 0xc1, 0x10, 0x04, 0xe6, 0x39, 0x71, 0x72, 0xb1, 0x27,
	0xe7, 0xe7, 0x95, 0xa4, 0xe6, 0x95, 0x28, 0xa9, 0x73, 0x09, 0xa2, 0xd9, 0x5d, 0x5c, 0x20, 0x24,
	0x04, 0xd5, 0x05, 0xb2, 0x96, 0x07, 0xa2, 0xc7, 0xa8, 0x94, 0x8b, 0xd5, 0x05, 0xe4, 0x77, 0xa1,
	0x1c, 0x2e, 0x5e, 0x14, 0x1d, 0x42, 0x9a, 0x38, 0x9d, 0x85, 0xee, 0x2b, 0x29, 0x2d, 0x62, 0x95,
	0x16, 0x17, 0x28, 0x31, 0x68, 0x30, 0x1a, 0x30, 0x3a, 0xe9, 0x46, 0x69, 0xa7, 0x67, 0x96, 0x64,
	0x94, 0x26, 0x81, 0x94, 0xea, 0x43, 0xb5, 0xc2, 0x68, 0xdd, 0xe4, 0x9c, 0x4c, 0xfd, 0xa2, 0x82,
	0x64, 0x7d, 0x98, 0x31, 0x49, 0x6c, 0xe0, 0x10, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x65,
	0x39, 0x3a, 0xc2, 0xb1, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DebugClient is the client API for Debug service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DebugClient interface {
	StreamingOpen(ctx context.Context, opts ...grpc.CallOption) (Debug_StreamingOpenClient, error)
}

type debugClient struct {
	cc *grpc.ClientConn
}

func NewDebugClient(cc *grpc.ClientConn) DebugClient {
	return &debugClient{cc}
}

func (c *debugClient) StreamingOpen(ctx context.Context, opts ...grpc.CallOption) (Debug_StreamingOpenClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Debug_serviceDesc.Streams[0], "/cc.arduino.cli.commands.Debug/StreamingOpen", opts...)
	if err != nil {
		return nil, err
	}
	x := &debugStreamingOpenClient{stream}
	return x, nil
}

type Debug_StreamingOpenClient interface {
	Send(*StreamingOpenReq) error
	Recv() (*StreamingOpenResp, error)
	grpc.ClientStream
}

type debugStreamingOpenClient struct {
	grpc.ClientStream
}

func (x *debugStreamingOpenClient) Send(m *StreamingOpenReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *debugStreamingOpenClient) Recv() (*StreamingOpenResp, error) {
	m := new(StreamingOpenResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DebugServer is the server API for Debug service.
type DebugServer interface {
	StreamingOpen(Debug_StreamingOpenServer) error
}

func RegisterDebugServer(s *grpc.Server, srv DebugServer) {
	s.RegisterService(&_Debug_serviceDesc, srv)
}

func _Debug_StreamingOpen_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DebugServer).StreamingOpen(&debugStreamingOpenServer{stream})
}

type Debug_StreamingOpenServer interface {
	Send(*StreamingOpenResp) error
	Recv() (*StreamingOpenReq, error)
	grpc.ServerStream
}

type debugStreamingOpenServer struct {
	grpc.ServerStream
}

func (x *debugStreamingOpenServer) Send(m *StreamingOpenResp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *debugStreamingOpenServer) Recv() (*StreamingOpenReq, error) {
	m := new(StreamingOpenReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Debug_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cc.arduino.cli.commands.Debug",
	HandlerType: (*DebugServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamingOpen",
			Handler:       _Debug_StreamingOpen_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "commands/debug.proto",
}
